name: Run Pokemon Scraper Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # At 00:00 on day 1 of each month (UTC)
  workflow_dispatch:     # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py

    - name: Upload output CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: scraper-output
        path: allcorectpricees.csv
